#include "NoteRepository.h"
#include "MarkdownUtils.h"
#include "CaptureContentFormatter.h"
#include "../utils/Utils.h"
#include "../utils/FileIO.h"
#include "../utils/CrashGuard.h"

#include <QDateTime>
#include <QFileInfo>
#include <QDir>
#include <QRegularExpression>

void NoteRepository::normalizeNoteFile(const QString &filePath) {
    if (filePath.isEmpty() || !formatter_)
        return;

    CrashGuard::safeCall([&]() {
        auto read = FileIO::readText(filePath);
        if (read.isFail() || read.value().isEmpty())
            return;

        const QString normalized = formatter_->normalizeContent(read.value());
        FileIO::writeTextAtomic(filePath, normalized + QLatin1Char('\n'));
    }, QStringLiteral("normalizeNoteFile"));
}

void NoteRepository::updateTocInFile(const QString &filePath, const QList<SectionItem> &sections) {
    if (filePath.isEmpty() || !formatter_)
        return;

    // Skip non-existent notes (new subject not yet written)
    if (!QFileInfo::exists(filePath))
        return;

    CrashGuard::safeCall([&]() {
        auto read = FileIO::readText(filePath);
        if (read.isFail())
            return;

        QString content = read.value();
        const QString rootImagesDir = QDir(notes_dir_path_).filePath(QStringLiteral("images"));
        static const QRegularExpression relative_img_regex(
            QStringLiteral("!\\[([^\\]]*)\\]\\((?!/)(?:.*?[/\\\\])?images[/\\\\](img_[^)]+)\\)"));
        content.replace(relative_img_regex, QStringLiteral("![\\1](%1/\\2)").arg(rootImagesDir));

        const QString updated = formatter_->updateTocInContent(content, sections);
        FileIO::writeTextAtomic(filePath, updated + QLatin1Char('\n'));
    }, QStringLiteral("updateTocInFile"));
}

QList<NoteItem> NoteRepository::parseNoteStructure(const QString &filePath,
                                                   const QList<SectionItem> &sections,
                                                   QSet<QString> &customAddedSections,
                                                   const QString &subjectName) {
    Q_UNUSED(subjectName);
    if (filePath.isEmpty() || !formatter_)
        return {};

    return CrashGuard::safeCallValue<QList<NoteItem>>([&]() -> QList<NoteItem> {
        auto read = FileIO::readText(filePath);
        if (read.isFail())
            return {};

        QList<NoteItem> items = formatter_->parseNoteStructure(read.value(), sections, customAddedSections);
        formatter_->saveStructureTree(filePath, items);
        return items;
    }, {}, QStringLiteral("parseNoteStructure"));
}

bool NoteRepository::writeImageToNote(const QString &targetFile, const QString &imageFilename,
                                      const QString &selectedSlug, QString &lastDate) {
    if (isUnselectedSubject(targetFile)) {
        return false;
    }

    // Image filenames are generated by the app (img_YYYYMMDD_hhmmss.png) —
    // still reject anything that looks like a path segment.
    if (imageFilename.contains(QLatin1Char('/')) || imageFilename.contains(QLatin1Char('\\'))
        || imageFilename.contains(QLatin1String(".."))) {
        return false;
    }

    return CrashGuard::safeCallValue<bool>([&]() -> bool {
        const QString absImagePath = QDir(notes_dir_path_).filePath(QStringLiteral("images/")) + escapeHtml(imageFilename);
        const QString imgMarkdown = QStringLiteral("\n![Image](%1)\n\n").arg(absImagePath);

        if (!selectedSlug.isEmpty()) {
            auto read = FileIO::readText(targetFile);
            if (read.isFail())
                return false;

            QString content = read.takeValue();

            int start_pos = -1;
            int end_pos = -1;
            bool is_html = false;
            int insert_pos = -1;

            if (MarkdownUtils::get_heading_bounds(content, selectedSlug, start_pos, end_pos, is_html)) {
                insert_pos = end_pos;
            } else if (!MarkdownUtils::get_subheading_insert_pos(content, selectedSlug, insert_pos)) {
                return false;
            }

            if (insert_pos >= 0 && insert_pos <= content.size()) {
                QString to_insert = imgMarkdown;
                if (insert_pos > 0 && content[insert_pos - 1] != QLatin1Char('\n'))
                    to_insert.prepend(QLatin1Char('\n'));
                content.insert(insert_pos, to_insert);
                return FileIO::writeTextAtomic(targetFile, content).isOk();
            }
        }

        lastDate = MarkdownUtils::restore_state_from_file(targetFile);

        auto read = FileIO::readText(targetFile);
        if (read.isFail())
            return false;

        QString content = read.takeValue();

        const QString current_date = QDateTime::currentDateTime().toString(QStringLiteral("dd MMMM, yyyy"));
        if (current_date != lastDate) {
            if (!content.isEmpty() && !content.endsWith(QLatin1Char('\n')))
                content += QLatin1Char('\n');
            content += QStringLiteral("\n### ***%1***\n").arg(current_date);
            lastDate = current_date;
        }

        content += imgMarkdown;
        return FileIO::writeTextAtomic(targetFile, content).isOk();
    }, false, QStringLiteral("writeImageToNote"));
}

bool NoteRepository::injectHeadingToNote(const QString &targetFile, const QString &simplifiedText,
                                         const QString &section, QString &lastDate) {
    if (isUnselectedSubject(targetFile)) {
        return false;
    }

    return CrashGuard::safeCallValue<bool>([&]() -> bool {
        // formatIndex 1 = main heading — shared formatter handles escaping + slug
        const QString block = CaptureContentFormatter::format(simplifiedText, /*formatIndex=*/1, section);
        if (block.isEmpty())
            return false;

        lastDate = MarkdownUtils::restore_state_from_file(targetFile);

        auto read = FileIO::readText(targetFile);
        if (read.isFail())
            return false;

        QString content = read.takeValue();

        const QString current_date = QDateTime::currentDateTime().toString(QStringLiteral("dd MMMM, yyyy"));
        if (current_date != lastDate) {
            if (!content.isEmpty() && !content.endsWith(QLatin1Char('\n')))
                content += QLatin1Char('\n');
            content += QStringLiteral("\n### ***%1***\n").arg(current_date);
            lastDate = current_date;
        }
        content += block;

        return FileIO::writeTextAtomic(targetFile, content).isOk();
    }, false, QStringLiteral("injectHeadingToNote"));
}
