#include "NoteRepository.h"
#include "MarkdownUtils.h"
#include "CaptureContentFormatter.h"
#include "../utils/Utils.h"
#include "../utils/FileIO.h"
#include "../utils/CrashGuard.h"

#include <QDateTime>
#include <QFileInfo>

void NoteRepository::normalizeNoteFile(const QString &filePath) {
    if (filePath.isEmpty() || !formatter_)
        return;

    CrashGuard::safeCall([&]() {
        auto read = FileIO::readText(filePath);
        if (read.isFail() || read.value().isEmpty())
            return;

        const QString normalized = formatter_->normalizeContent(read.value());
        FileIO::writeTextAtomic(filePath, normalized + QLatin1Char('\n'));
    }, QStringLiteral("normalizeNoteFile"));
}

void NoteRepository::updateTocInFile(const QString &filePath, const QList<SectionItem> &sections) {
    if (filePath.isEmpty() || !formatter_)
        return;

    // Skip non-existent notes (new subject not yet written)
    if (!QFileInfo::exists(filePath))
        return;

    CrashGuard::safeCall([&]() {
        auto read = FileIO::readText(filePath);
        if (read.isFail())
            return;

        const QString updated = formatter_->updateTocInContent(read.value(), sections);
        FileIO::writeTextAtomic(filePath, updated + QLatin1Char('\n'));
    }, QStringLiteral("updateTocInFile"));
}

QList<NoteItem> NoteRepository::parseNoteStructure(const QString &filePath,
                                                   const QList<SectionItem> &sections,
                                                   QSet<QString> &customAddedSections,
                                                   const QString &subjectName) {
    Q_UNUSED(subjectName);
    if (filePath.isEmpty() || !formatter_)
        return {};

    return CrashGuard::safeCallValue<QList<NoteItem>>([&]() -> QList<NoteItem> {
        auto read = FileIO::readText(filePath);
        if (read.isFail())
            return {};

        QList<NoteItem> items = formatter_->parseNoteStructure(read.value(), sections, customAddedSections);
        formatter_->saveStructureTree(filePath, items);
        return items;
    }, {}, QStringLiteral("parseNoteStructure"));
}

bool NoteRepository::writeImageToNote(const QString &targetFile, const QString &imageFilename,
                                      QString &lastDate) {
    if (isUnselectedSubject(targetFile)) {
        return false;
    }

    // Image filenames are generated by the app (img_YYYYMMDD_hhmmss.png) —
    // still reject anything that looks like a path segment.
    if (imageFilename.contains(QLatin1Char('/')) || imageFilename.contains(QLatin1Char('\\'))
        || imageFilename.contains(QLatin1String(".."))) {
        return false;
    }

    return CrashGuard::safeCallValue<bool>([&]() -> bool {
        lastDate = MarkdownUtils::restore_state_from_file(targetFile);

        auto read = FileIO::readText(targetFile);
        if (read.isFail())
            return false;

        QString content = read.takeValue();

        const QString current_date = QDateTime::currentDateTime().toString(QStringLiteral("dd MMMM, yyyy"));
        if (current_date != lastDate) {
            if (!content.isEmpty() && !content.endsWith(QLatin1Char('\n')))
                content += QLatin1Char('\n');
            content += QStringLiteral("\n### ***%1***\n").arg(current_date);
            lastDate = current_date;
        }

        content += QStringLiteral("\n![Image](images/%1)\n\n").arg(escapeHtml(imageFilename));
        return FileIO::writeTextAtomic(targetFile, content).isOk();
    }, false, QStringLiteral("writeImageToNote"));
}

bool NoteRepository::injectHeadingToNote(const QString &targetFile, const QString &simplifiedText,
                                         const QString &section, QString &lastDate) {
    if (isUnselectedSubject(targetFile)) {
        return false;
    }

    return CrashGuard::safeCallValue<bool>([&]() -> bool {
        // formatIndex 1 = main heading — shared formatter handles escaping + slug
        const QString block = CaptureContentFormatter::format(simplifiedText, /*formatIndex=*/1, section);
        if (block.isEmpty())
            return false;

        lastDate = MarkdownUtils::restore_state_from_file(targetFile);

        auto read = FileIO::readText(targetFile);
        if (read.isFail())
            return false;

        QString content = read.takeValue();

        const QString current_date = QDateTime::currentDateTime().toString(QStringLiteral("dd MMMM, yyyy"));
        if (current_date != lastDate) {
            if (!content.isEmpty() && !content.endsWith(QLatin1Char('\n')))
                content += QLatin1Char('\n');
            content += QStringLiteral("\n### ***%1***\n").arg(current_date);
            lastDate = current_date;
        }
        content += block;

        return FileIO::writeTextAtomic(targetFile, content).isOk();
    }, false, QStringLiteral("injectHeadingToNote"));
}
